---
name: WorldEditArt
author: PEMapModder
version: 1.0.0_beta_dev_#048
api:
- 1.0.0
load: POSTWORLD
main: pemapmodder\worldeditart\WorldEditArt
description: A powerful advanced world editor
website: https://github.com/PEMapModder/Small-ZC-Plugins/tree/master/WorldEditArt
permissions:
  wea:
    description: Allows using all WorldEditArt commands
    children:
      wea.cmd:
        description: Allows using the command
      wea.anchor:
        description: Allows using //anchor
      wea.copy:
        description: Allows using //copy
      wea.cuboid:
        description: Allows using //cuboid
      wea.cut:
        description: Allows using //cut
      wea.cylinder:
        description: Allows using //cylinder
      wea.desel:
        description: Allows using //desel
      wea.macro:
        description: Allows using all subcommands of //macro
        children:
          wea.macro.start:
            description: Allows using //macro start
          wea.macro.end:
            description: Allows ending a macro by all means
            children:
              wea.macro.end.ng:
                description: Allows using //macro ng
                default: true
              wea.macro.end.save:
                description: Allows using //macro save
          wea.macro.wait:
            description: Allows using //macro wait
          wea.macro.pause:
            descrition: Allows using //macro pause
          wea.macro.resume:
            description: Allows using //macro resume
      wea.paste:
        description: Allows using //paste
      wea.pos:
        description: Allows using //pos1 and //pos2
      wea.replace:
        description: Allows using //replace on all shapes of selections
        children:
          wea.replace.cuboid:
            description: Allows using //replace for cuboid selections
          wea.replace.cylinder:
            description: Allows using //replace for cylinder selections
          wea.replace.sphere:
            description: Allows using //replace for sphere selections
      wea.tool:
        description: Allows using all subcommands that modify selected tools
        children:
          wea.tool.jump:
            description: Allows using //jump
          wea.tool.wand:
            description: Allows using //wand
      wea.set:
        description: Allows using //set on all shapes of selections
        children:
          wea.set.cuboid:
            description: Allows using //set for cuboid selections
          wea.set.cylinder:
            description: Allows using //set for cylinder selections
          wea.set.sphere:
            description: Allows using //set for sphere selections
      wea.sphere:
        description: Allows using //sphere
      wea.test:
        description: Allows using //test on all shapes of selections
        children:
          wea.test.cuboid:
            description: Allows using //test for cuboid selections
          wea.test.cylinder:
            description: Allows using //test for cylinder selections
          wea.test.sphere:
            description: Allows using //test for sphere selections
...
